### PR TITLE
add install script to check existence of MSVCR120.dll

### PR DESCRIPTION
**Pull request by okdshin**

### CODE REVIEW

**Comment by msakai** [comment]
I experimented installation of resulting package on AppVeyor using the commit 7f6b6dcf8168248360aba7ce5c51334235b18de7 .

The result is https://ci.appveyor.com/project/msakai/mkl-dnn/build/1.0.28 : 

```
pacman -U --noconfirm mingw-w64-x86_64-mkl-dnn-*.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...
Packages (1) mingw-w64-x86_64-mkl-dnn-0.16-2
Total Installed Size:  123.98 MiB
:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing mingw-w64-x86_64-mkl-dnn...
```

Neither of the messages were displayed.

Do you have any ideas? @okdshin @Hakuyume

**Comment by msakai** [comment]
This time the result is the following:

https://ci.appveyor.com/project/msakai/mkl-dnn/build/1.0.30
```
pacman -U --noconfirm mingw-w64-x86_64-mkl-dnn-*.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...
Packages (1) mingw-w64-x86_64-mkl-dnn-0.16-2
Total Installed Size:  123.98 MiB
:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing mingw-w64-x86_64-mkl-dnn...
ldd: /bin/libmkldnn.dll: No such file or directory
libmkldnn depends on MSVCR120.dll but it is not found.
MSVCR120.dll is contained in Microsoft Visual Studio 2013 Runtime Package.
Please download from https://www.microsoft.com/en-us/download/details.aspx?id=40784 and install it.
```

Now, the function is called, but it seems that `${pkgdir}` and `${MINGW_PREFIX}` are not defined when the function is called.

**Comment by msakai** [comment]
It seems that following is a simple way to test the existence of `MSVCR120.dll`.

```
which MSVCR120.dll
if [ $? = 0 ]; then
    echo "MSVCR120.dll is found."
else
    echo "MSVCR120.dll is not found."
fi
```

**Comment by okdshin** [comment]
Thanks. I succeeded.

**Comment by msakai** [comment]
Thanks. It looks good to me.
To tidy up the code and the history, could you rewrite `mkl-dnn.install` to `${_realname}.install` and squash these commit into a single commit?

**Comment by msakai** [comment]
Merged!
Thanks a lot.

**Pull request merged**
